swagger: "2.0"
info:
    title: Lasting Dynamics Example Service
    description: This service is a simple example of my backend template implementation.
    version: 0.0.1
host: localhost:9090
basePath: /api/v1
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /training-plans:
        get:
            tags:
                - training_plan
            summary: list training_plan
            operationId: training_plan#list
            parameters:
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/TrainingPlan'
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
        post:
            tags:
                - training_plan
            summary: create training_plan
            operationId: training_plan#create
            parameters:
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TrainingPlanCreateRequestBody'
                    required:
                        - name
                        - startDate
                        - endDate
                        - userId
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/TrainingPlan'
                        required:
                            - id
                            - name
                            - startDate
                            - endDate
                            - userId
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
    /training-plans/{id}:
        get:
            tags:
                - training_plan
            summary: get training_plan
            operationId: training_plan#get
            parameters:
                - name: id
                  in: path
                  description: Training plan ID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TrainingPlan'
                        required:
                            - id
                            - name
                            - startDate
                            - endDate
                            - userId
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
        put:
            tags:
                - training_plan
            summary: update training_plan
            operationId: training_plan#update
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TrainingPlanUpdateRequestBody'
                    required:
                        - name
                        - startDate
                        - endDate
                        - userId
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TrainingPlan'
                        required:
                            - id
                            - name
                            - startDate
                            - endDate
                            - userId
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
        delete:
            tags:
                - training_plan
            summary: delete training_plan
            operationId: training_plan#delete
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
    /user:
        get:
            tags:
                - user
            summary: list user
            description: List all users with pagination
            operationId: user#list
            parameters:
                - name: limit
                  in: query
                  description: Number of users to return per page
                  required: false
                  type: integer
                  default: 10
                  maximum: 100
                  minimum: 1
                - name: offset
                  in: query
                  description: Number of users to skip
                  required: false
                  type: integer
                  default: 0
                  minimum: 0
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/User'
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
        post:
            tags:
                - user
            summary: create user
            description: Create a new user
            operationId: user#create
            parameters:
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserCreateRequestBody'
                    required:
                        - firstName
                        - lastName
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/User'
                        required:
                            - id
                            - kcId
                            - firstName
                            - lastName
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
    /user/{id}:
        get:
            tags:
                - user
            summary: get user
            description: Get a user by ID
            operationId: user#get
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/User'
                        required:
                            - id
                            - kcId
                            - firstName
                            - lastName
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequest'
                        required:
                            - name
                            - id
                            - message
                            - temporary
                            - timeout
                            - fault
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/Unauthorized'
                        required:
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFound'
                        required:
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - message
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
        put:
            tags:
                - user
            summary: update user
            description: Update a user
            operationId: user#update
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserUpdateRequestBody'
                    required:
                        - firstName
                        - lastName
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/User'
                        required:
                            - id
                            - kcId
                            - firstName
                            - lastName
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequest'
                        required:
                            - name
                            - id
                            - message
                            - temporary
                            - timeout
                            - fault
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/Unauthorized'
                        required:
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFound'
                        required:
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - message
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
        delete:
            tags:
                - user
            summary: delete user
            description: Delete a user
            operationId: user#delete
            parameters:
                - name: id
                  in: path
                  description: User ID
                  required: true
                  type: string
                  format: uuid
                - name: Authorization
                  in: header
                  description: OAuth2 access token used to perform authorization
                  required: false
                  type: string
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BadRequest'
                        required:
                            - name
                            - id
                            - message
                            - temporary
                            - timeout
                            - fault
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/Unauthorized'
                        required:
                            - message
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFound'
                        required:
                            - message
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalServerError'
                        required:
                            - message
            schemes:
                - http
            security:
                - oauth2_header_Authorization:
                    - openid
definitions:
    BadRequest:
        title: BadRequest
        type: object
        properties:
            fault:
                type: boolean
                description: Indica se l'errore è dovuto a un problema del server
                example: false
            id:
                type: string
                description: ID dell'errore
                example: Aonp24i2
            message:
                type: string
                description: Descrizione dettagliata dell'errore
                example: ID must be greater or equal than 1 but got value -1
            name:
                type: string
                description: Nome dell'errore
                example: invalid_range
            temporary:
                type: boolean
                description: Indica se l'errore è temporaneo
                example: false
            timeout:
                type: boolean
                description: Indica se l'errore è dovuto a un timeout
                example: false
        description: Parametri non validi
        example:
            fault: false
            id: Aonp24i2
            message: ID must be greater or equal than 1 but got value -1
            name: invalid_range
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    InternalServerError:
        title: InternalServerError
        type: object
        properties:
            message:
                type: string
                description: Descrizione dell'errore
                default: Errore di comunicazione con il server
                example: Est earum.
        description: Errore nel server
        example:
            message: Excepturi rem autem.
        required:
            - message
    NotFound:
        title: NotFound
        type: object
        properties:
            message:
                type: string
                description: Descrizione dell'errore
                default: Dato non trovato
                example: Nobis non suscipit.
        description: Dato non trovato all'interno del sistema
        example:
            message: Placeat omnis ut iusto.
        required:
            - message
    TrainingPlan:
        title: TrainingPlan
        type: object
        properties:
            description:
                type: string
                description: Description of the plan
                example: A 4-week plan focused on upper body hypertrophy.
            endDate:
                type: string
                description: End date in ISO 8601
                example: "2025-04-25T00:00:00Z"
                format: date-time
            id:
                type: string
                description: TrainingPlan ID
                example: 11111111-2222-3333-4444-555555555555
                format: uuid
            name:
                type: string
                description: Name of the training plan
                example: Upper Body Strength
            startDate:
                type: string
                description: Start date in ISO 8601
                example: "2025-03-25T00:00:00Z"
                format: date-time
            userId:
                type: string
                description: ID of the user who owns the plan
                example: 550e8400-e29b-41d4-a716-446655440000
                format: uuid
        example:
            description: A 4-week plan focused on upper body hypertrophy.
            endDate: "2025-04-25T00:00:00Z"
            id: 11111111-2222-3333-4444-555555555555
            name: Upper Body Strength
            startDate: "2025-03-25T00:00:00Z"
            userId: 550e8400-e29b-41d4-a716-446655440000
        required:
            - id
            - name
            - startDate
            - endDate
            - userId
    TrainingPlanCreateRequestBody:
        title: TrainingPlanCreateRequestBody
        type: object
        properties:
            description:
                type: string
                description: Description
                example: A plan for strength.
            endDate:
                type: string
                example: "2025-04-25T00:00:00Z"
                format: date-time
            name:
                type: string
                description: Name of the plan
                example: Upper Body Strength
                minLength: 1
            startDate:
                type: string
                example: "2025-03-25T00:00:00Z"
                format: date-time
            userId:
                type: string
                example: 550e8400-e29b-41d4-a716-446655440000
                format: uuid
        example:
            description: A plan for strength.
            endDate: "2025-04-25T00:00:00Z"
            name: Upper Body Strength
            startDate: "2025-03-25T00:00:00Z"
            userId: 550e8400-e29b-41d4-a716-446655440000
        required:
            - name
            - startDate
            - endDate
            - userId
    TrainingPlanUpdateRequestBody:
        title: TrainingPlanUpdateRequestBody
        type: object
        properties:
            description:
                type: string
                description: Description
                example: A plan for strength.
            endDate:
                type: string
                example: "2025-04-25T00:00:00Z"
                format: date-time
            name:
                type: string
                description: Name of the plan
                example: Upper Body Strength
                minLength: 1
            startDate:
                type: string
                example: "2025-03-25T00:00:00Z"
                format: date-time
            userId:
                type: string
                example: 550e8400-e29b-41d4-a716-446655440000
                format: uuid
        example:
            description: A plan for strength.
            endDate: "2025-04-25T00:00:00Z"
            name: Upper Body Strength
            startDate: "2025-03-25T00:00:00Z"
            userId: 550e8400-e29b-41d4-a716-446655440000
        required:
            - name
            - startDate
            - endDate
            - userId
    Unauthorized:
        title: Unauthorized
        type: object
        properties:
            message:
                type: string
                description: Descrizione dell'errore
                default: Utente già registrato a
                example: Aut dignissimos minima.
        description: Autenticazione fallita
        example:
            message: Est impedit qui inventore ipsam est qui.
        required:
            - message
    User:
        title: User
        type: object
        properties:
            admin:
                type: boolean
                description: Is the user an admin?
                default: false
                example: false
            firstName:
                type: string
                description: First name of the user
                example: John
            id:
                type: string
                description: Unique ID of the user
                example: f47ac10b-58cc-4372-a567-0e02b2c3d479
                format: uuid
            kcId:
                type: string
                description: Keycloak ID
                example: 550e8400-e29b-41d4-a716-446655440000
                format: uuid
            lastName:
                type: string
                description: Last name of the user
                example: Doe
            nickname:
                type: string
                description: Nickname
                example: JD
        example:
            admin: false
            firstName: John
            id: f47ac10b-58cc-4372-a567-0e02b2c3d479
            kcId: 550e8400-e29b-41d4-a716-446655440000
            lastName: Doe
            nickname: JD
        required:
            - id
            - kcId
            - firstName
            - lastName
    UserCreateRequestBody:
        title: UserCreateRequestBody
        type: object
        properties:
            admin:
                type: boolean
                description: Is admin?
                default: false
                example: false
            firstName:
                type: string
                description: First name
                example: John
            lastName:
                type: string
                description: Last name
                example: Doe
            nickname:
                type: string
                description: Nickname
                example: JD
                maxLength: 16
            password:
                type: string
                description: User password
                example: Secret!1
                pattern: ^[a-zA-Z0-9!@#\$%\^&\*\(\)_\+\-=\[\]{};':"\\|,.<>\/?]{6,}$
                minLength: 6
        example:
            admin: false
            firstName: John
            lastName: Doe
            nickname: JD
            password: Secret!1
        required:
            - firstName
            - lastName
    UserUpdateRequestBody:
        title: UserUpdateRequestBody
        type: object
        properties:
            admin:
                type: boolean
                description: Is admin?
                default: false
                example: false
            firstName:
                type: string
                description: First name
                example: John
            lastName:
                type: string
                description: Last name
                example: Doe
            nickname:
                type: string
                description: Nickname
                example: JD
        example:
            admin: false
            firstName: John
            lastName: Doe
            nickname: JD
        required:
            - firstName
            - lastName
securityDefinitions:
    oauth2_header_Authorization:
        type: oauth2
        description: OAuth2 flow
        flow: accessCode
        authorizationUrl: https://keycloak.example.com/realms/myrealm/protocol/openid-connect/auth
        tokenUrl: https://keycloak.example.com/realms/myrealm/protocol/openid-connect/token
        scopes:
            openid: Access basic profile
